// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPJZWcOtcqO7F6s5t4QXGZEk8NwNUwHzE',
    appId: '1:378684653165:web:c011160d970d83685e0964',
    messagingSenderId: '378684653165',
    projectId: 'bffsocialapp',
    authDomain: 'bffsocialapp.firebaseapp.com',
    storageBucket: 'bffsocialapp.appspot.com',
    measurementId: 'G-SYSME53EZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDU36z9xlyTcaZzBbxXCbtageFgmbl_Xk',
    appId: '1:378684653165:android:152945dbfbd033295e0964',
    messagingSenderId: '378684653165',
    projectId: 'bffsocialapp',
    storageBucket: 'bffsocialapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnfeb9AWAKdfdznZ_L83dA5gSb9UM1LAs',
    appId: '1:378684653165:ios:7e4876eed9980bdf5e0964',
    messagingSenderId: '378684653165',
    projectId: 'bffsocialapp',
    storageBucket: 'bffsocialapp.appspot.com',
    iosBundleId: 'com.example.bffDemoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnfeb9AWAKdfdznZ_L83dA5gSb9UM1LAs',
    appId: '1:378684653165:ios:76c540c45e9294875e0964',
    messagingSenderId: '378684653165',
    projectId: 'bffsocialapp',
    storageBucket: 'bffsocialapp.appspot.com',
    iosBundleId: 'com.example.bffDemoApp.RunnerTests',
  );
}
